### ISSUE TITLE
Modification methods wrong overwrite properties in the current model.

### ISSUE THREAD

**Issue by rkorolov** [creocoder/yii2-nested-sets#10]
moveAsLast and moveAsFirst methods working as expected but after initialization they incorrectly overwrite 'lft' and 'rgt' properties in the current model.
And when I update my model (saveNode()), correct property in the table overwrites whith this wrong data.
There is problem with method correctCachedOnMoveNode(), when I turn it of , methods start working properly.

**Comment by creocoder** [comment]
There is no more internal cache. Its planned as depency. Also behavior can be used without any cache for now. So we can complettely forget about troubles like this in future.
