### ISSUE TITLE
On Going or Dead?

### ISSUE THREAD

**Issue by KnightYoshi** [creocoder/yii2-nested-sets#111]
Is this library still supported? Do you have plans to expand it?

I saw this [PR](https://github.com/creocoder/yii2-nested-sets/pull/68) about external roots, was that implemented or is it still going to be implemented? I have a table for groups (roots) separate from the descendants because they're not the same data (navigation links and navigation groups); so, I'm curious about this.

**Comment by samdark** [comment]
@Knight-Yoshi do you want to support it? I have @creocoder personal contacts and may ask him to add more maintainers...

**Comment by KnightYoshi** [comment]
@samdark I'm not sure I have the skill set to be able to be able maintain it. I have little experience with doubly linked lists, but I'd like to see this library prosper. I think it has a lot of potential.

**Comment by samdark** [comment]
@creocoder is too busy with fulltime job as far as I know. If there will be another interested maintainer then I'll ping him about it.

I'm personally using the library as well but have no issues that affect me so far so not really interested in doing fixed beyond my use cases (doing that for Yii already, one huge project is enough).

**Comment by KnightYoshi** [comment]
Yeah. I think for my use case it just needs external roots. Other than that it seems to work quite well.
I'll take a look at it some time and see if I can add external roots, but I feel that's going to be quite a bit of work. Right now I'm busy though, classes just started and I have my projects to work on.

**Comment by schmunk42** [comment]
I got *write* access a while ago, along with https://github.com/creocoder/yii2-flysystem - please let me know if you see problematic issues.
