### ISSUE TITLE
Must be 'Menu' class?

### ISSUE THREAD

**Issue by gvanto** [creocoder/yii2-nested-sets#113]
I have a set of activerecord models that I would like to categorize (only 2 levels deep but possibly more in the future) and thinking of using this nested sets lib ... (to assign my models a category somehow, still need to figure out how, probably a single model->hasOne(category) relationship will do)

I noticed in the Readme it says to create "new Menu([options])" - can this class be called something else (like "Category") whereby I mean can I call the class whatever I like?

Thanks help appreciated,
g

**Comment by Mihai-P** [comment]
Yes, you can name the model in any way you desire. The point of this behavior is that you can attach it to any model and it makes the model work with nested sets. 

I use it as product categories, website menus, a restaurant menu (first level are the times of day, the second the categories, the 3rd level the meals), etc. None of my models are actually called "Menu".

**Comment by gvanto** [comment]
Awesome thanks @Mihai-P this what I was hoping for ...

If you don't mind can I ask how you link your products to product categories?  I have a model called BlogSite (resembles a blog/website) which I want to categorize and have it listed under a directory with something like /directory/{cat_level_1}  and /directory{cat_level_1}/{cat_level_2} which lists the appropriate blogSites.

**Comment by Mihai-P** [comment]
I have not done that, but you could try using the sluggable behavior http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html .

**Comment by gvanto** [comment]
Cool thanks will check it out.

How if I may ask do you link your products to categories?

**Comment by Mihai-P** [comment]
Depends on the requirements, sometimes the products table have a category_id field (when products belong to 1 category only) or with a category_product relationship table when a product can belong to multiple categories.

**Comment by gvanto** [comment]
OK thanks much thought that might be case just wanted to confirm :D
