### ISSUE TITLE
вывод на view дерево 

### ISSUE THREAD

**Issue by asder117** [creocoder/yii2-nested-sets#121]
Доброе время суток. А как можно дерево в виде меню вывести на форму?

**Comment by schmunk42** [comment]
It depends how you want to "store" the data in the form.
There are JavaScript libs which display a menu, but you have to convert the data on your own.

Presenting the tree data in a form is outside of this library's scope.

---

Это зависит от того, как вы хотите "хранить" данные в форме.
Существуют библиотеки JavaScript, которые отображают меню, но вам придется преобразовывать данные самостоятельно.

Представление данных дерева в форме выходит за рамки этой библиотеки.

auto translated with https://www.deepl.com/
