### ISSUE TITLE
On Many Roots tree, the nested set seem not work

### ISSUE THREAD

**Issue by dinhtrung** [creocoder/yii2-nested-sets#14]
Try the following sample data:

~~~
-- Root1
-- -- Branch1
-- -- -- Leaf1
-- Root2
~~~
Now move Root2 to Leaf1 then move it back to root once again.

This time, using Tree::find()->roots()->all() will only list Root1 as the root node.

Also the descendants() and ancestors() not working any more.

Any suggestion on fixing this?

**Comment by creocoder** [comment]
Fixed by complete overhaul for Yii 2 release version.
