### ISSUE TITLE
Multiple addition to $_cached.

### ISSUE THREAD

**Issue by juffin-halli** [creocoder/yii2-nested-sets#21]
Owner added to $_cached first time after attaching behavior (ensureBevaviors calls $behavior->attach) and second time by processing aterFind event. Is it correct? There is another issue https://github.com/creocoder/yii2-nested-set-behavior/issues/19 - may be it's caused by second cache correction?

**Comment by creocoder** [comment]
There is no more internal cache inside behavior for Yii 2 release version. Cache is planned like external depency for release version.
