### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by juffin-halli** [creocoder/yii2-nested-sets#22]
$_cached values could be cleared only in destructor method, meanwhile behavior might already detached and owner property will be nulled, so get_class($this->owner) values will be wrong. Also, maybe, it is sensible to clear $_cached values with behavior detaching .

**Comment by creocoder** [comment]
There is no more possible memory leaks inside behavior for Yii 2 release version. Also working approach was changed. We can complettely forget about troubles like this.
