### ISSUE TITLE
Possible `NestedSet::moveAsFirst()` bug

### ISSUE THREAD

**Issue by mobius77** [creocoder/yii2-nested-sets#34]
When use this function it sets wrong lft and rgt values. (in example 12, 13 but it must be 10, 11)
![20-12-2014 14-20-58](https://cloud.githubusercontent.com/assets/10038730/5514786/ab54db80-8853-11e4-8065-9276ce9b28ed.jpg)

**Comment by creocoder** [comment]
There is no more `moveAsFirst` method inside behavior for Yii 2 release version. Also working approach was changed so there is now tree integrity garantee. We can complettely forget about troubles like this.

**Comment by mobius77** [comment]
And how now i must move node as first?
