### ISSUE TITLE
Implement `moveBefore($node,...)` & `moveAfter($node,...)`

### ISSUE THREAD

**Issue by AlexGx** [creocoder/yii2-nested-sets#46]
I`m porting my yii1.1 stuff to yii2.
Any plans on this functions?

**Comment by AlexGx** [comment]
I`m found that insertBefore/After behave same. Sorry =).
closed.

**Comment by creocoder** [comment]
@AlexGx Yeah, api become more short now. You can insert new node and move exists node with same methods now )
