### ISSUE TITLE
Getting the whole tree example?

### ISSUE THREAD

**Issue by eudj1n** [creocoder/yii2-nested-sets#48]
Please, add examples for getting the whole tree.

**Comment by yakovlev-vladimir** [comment]
$categories = MarketCategory::find()->all();
$depth = 0;

foreach ($categories as $n => $category)
{
    if ($category->depth == $depth) {
        echo Html::endTag('li') . "\n";
    } elseif ($category->depth > $depth) {
        echo Html::beginTag('ul') . "\n";
    } else {
        echo Html::endTag('li') . "\n";

        for ($i = $level - $category->depth; $i; $i--) {
            echo Html::endTag('ul') . "\n";
            echo Html::endTag('li') . "\n";
        }
    }

    echo Html::beginTag('li');
    echo Html::encode($category->title);
    $depth = $category->depth;
}

for ($i = $depth; $i; $i--) {
    echo Html::endTag('li') . "\n";
    echo Html::endTag('ul') . "\n";
}

**Comment by wokster** [comment]
not right
 result:
1
2
  1.1

**Comment by ptheofan** [comment]
I have copied there a trait that I have created and commonly use with my classes that use the NestedSet behavior. Amongst other things you can generate export as nested array, flat array, flat array for jsTree json data, etc.

https://gist.github.com/ptheofan/d6760ebbaf2371c75c62

**Comment by creocoder** [comment]
Algorithm provided by @yakovlev-vladimir is correct, but instead of

```php
$categories = MarketCategory::find()->all();
```

it can be

```php
$categories = MarketCategory::find()->roots()->children();
```

if you need tree without root with correct order and

```php
$categories = MarketCategory::find()->orderBy(['lft' => SORT_ASC])->all();
```

if you need just correct order.

**Comment by wokster** [comment]
i create widget for right view and conect it with sortable jquery plagin. Work fine. Thanks.
