### ISSUE TITLE
How about allowing to modify the id attribute?

### ISSUE THREAD

**Issue by ptheofan** [creocoder/yii2-nested-sets#50]
Hey mate, I see you're going a nice way allowing people to modify specific column names. How about allowing to modify and configure the `id` attribute? For example, I would love to change it to `id_xxxxxx` to match the rest of the schema.

Cheers,
P.

**Comment by creocoder** [comment]
@ptheofan Hi, you can use any primary key field name without any troubles and without reconfiguring behavior.
