### ISSUE TITLE
Is Separate Query Behavior Really Necessary?

### ISSUE THREAD

**Issue by angelcoding** [creocoder/yii2-nested-sets#61]
I'm just wondering why a separate Query behavior is needed when you could simply add those functions to the main AR behavior and just use that without having to extend ActiveQuery and add a second behavior?
e.g move roots function to NestedSetsBehavior (would be similar for leaves() function too) ...

```php
    /**
	 * Gets root node(s).
	 * @return ActiveQuery.
	 */
	public function roots()
	{
		$query = $this->owner->find();

		$query->andWhere([$this->leftAttribute => 1])
              ->addOrderBy([$this->owner->primaryKey()[0] => SORT_ASC]);

		return $query;
	}
```
Am I wrong in thinking this?

**Comment by creocoder** [comment]
Its absoluttely neccesary. Moreover its normal to have Query model if you want scopes feature for example. Also look query `leaves()` and `roots()` usage documentation. Its work like `Category::find()->roots()` or `Category::find()->leaves()` while ActiveRecord behavior need instance. We do not have instance in such cases.

**Comment by angelcoding** [comment]
Aaah OK, thanks for clearing that up. I can see the advantage now when using static class methods.
