### ISSUE TITLE
Валится структура

### ISSUE THREAD

**Issue by set-st** [creocoder/yii2-nested-sets#63]
Приветствую. Есть ли какая информация как изменить родителя ветви?
Если использовать $category->appendTo($root) то спонтанно валится структура (иногда да иногда нет), и ветвь исчезает. В базе есть но уровень не тот.

Как правильно добавить новую ветвь к указанному родителю и как изменить существующую с переносом на другого родителя?

**Comment by creocoder** [comment]
> В базе есть но уровень не тот.

Использовалась ли ранее таблица с данным деревом с расширением под Yii 1? Если да, то расширение для Yii 2 не использует больше level, тут есть depth, который считается по другому.

**Comment by creocoder** [comment]
> Как правильно добавить новую ветвь к указанному родителю и как изменить существующую с переносом на другого родителя?

Для этого есть 4 метода: `prependTo`, `appendTo`, `insertBefore`, `insertAfter` Добавление новой ветви и её перенос осуществляется одним и тем же методом. Убедитесь что у вас поле `depth` имеет корректные значения.
