### ISSUE TITLE
add support for deleting a root node

### ISSUE THREAD

**Issue by schmunk42** [creocoder/yii2-nested-sets#71]
I got this error with `0.9.0`

    Method "dmstr\modules\pages\models\Tree::delete" is not supported for deleting root node.

```
Stack trace:
#0 [internal function]: creocoder\nestedsets\NestedSetsBehavior-&gt;beforeDelete(Object(yii\base\ModelEvent))
#1 /app/vendor/yiisoft/yii2/base/Component.php(538): call_user_func(Array, Object(yii\base\ModelEvent))
....
```

Is there a special reason why this is denied?

**Comment by creocoder** [comment]
@schmunk42 Use `deleteWithChildren` for it. Method `delete` remove only one node and move its children to same level. Its not possible for root nodes. While `deleteWithChildren` remove node and its children complettely. You can find same different removing strategy in other NS implementations.

**Comment by schmunk42** [comment]
Thanks, I didn't recognize that.

**Comment by cornernote** [comment]
This should be in the documentation.  I had the same issue.
