### ISSUE TITLE
Nested set Parent relation

### ISSUE THREAD

**Issue by Velm14** [creocoder/yii2-nested-sets#75]
Hello to everyone, I really need parent relation in nested set Yii2, I done this in Yii1.0.1, but how I can do this in second version. If developers read it, pls make a chance to do Eager loading parent in Yii2
I am missing "parent" relation. I mean, that I can not do Eager loading in relation ( I canno't write such relation )

**Comment by creocoder** [comment]
Can you provide more details? You can get parent by using corresponding method.

**Comment by Velm14** [comment]
no-no, I want to do it with Eager loading, I want to degreese count of queries

**Comment by Velm14** [comment]
such as joinWith('parent')

**Comment by creocoder** [comment]
To define relations you need foreign keys. Nested Sets by its nature do not work with node foreign keys. So you have option like add additional `parent_id` column and corresponding logic to model to control it.

**Comment by Velm14** [comment]
You say that I must reset value of 'parent_id' every time when I change my node ?

**Comment by creocoder** [comment]
As i said before if you need relation you need foreign key. How you will control `parent_id` its your own choice. Such functionality is very specific and out of nested set behavior responsibility.
