### ISSUE TITLE
Move root nodes 

### ISSUE THREAD

**Issue by webadequate** [creocoder/yii2-nested-sets#81]
Планируется ли сделать перемещение root узлов?

Для первой версии некоторые делали вот так: http://www.yiilearning.com/nestedsetbehavior-move-root-nodes-many-roots-modesolved/

**Comment by gglp** [comment]
Для root-узлов не предусмотрено упорядочивание (Была по этому поводу Задача #2).
Если нужно упорядочивать узлы, они должны быть потомками.

**Comment by creocoder** [comment]
Нет, не планируется, т.к. эта задача решается использованием расширения в режиме single tree.

**Comment by Urmuz** [comment]
Можно сделать иначе. Вот следующий пример. Создаем root меню (Top Menu например). И внутри него уже располагаем все. Отключаем возможность удаления данного root раздела. Примерная схема выглядит так:
![2018-01-29_15-49-02](https://user-images.githubusercontent.com/4378793/35509012-0236c6ba-050c-11e8-8baa-2712f27d9c1b.png)

Данное решение вполне рабочее в данном случае.
