### ISSUE TITLE
Использование в миграциях

### ISSUE THREAD

**Issue by Oreolek** [creocoder/yii2-nested-sets#88]
Как использовать модуль в миграциях? 

```
$root = new Category(['name' => 'Корень']);
$root->makeRoot();
$root->save();
```

Не сохраняет [Postgresql]

UPD: всё норм, валидация не проходила.

**Comment by t-kanstantsin** [comment]
Использование моделей в миграциях - первый шаг к тому, что миграции не будут выполняться.
"завтра" изменится поведение модели Category и эта миграция отвалится.
